apiVersion: v1
kind: Service
metadata:
  name: csye7374-lb-gsvc
spec:
  type: LoadBalancer            
  ports:
  - name: http
    protocol: TCP
    port: 80                 
    targetPort: 3000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3000        
  selector:
    app: grafana