---

- name: Generate password for grafana login for admin user
  shell: kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode 
  register: adminpwd

- debug:
    msg: "Password is {{adminpwd.stdout}}" 

- name: Create idatasource
  grafana_datasource:
    name: "DS_PROMETHEUS"
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{adminpwd.stdout}}"
    org_id: "1"
    ds_type: "prometheus"
    url: "http://localhost:9090"
    access: "direct"
    