---

- name: Fetching aws account id
  shell: aws sts get-caller-identity --output text --query 'Account'
  register: accountid1


- name: Run Secret file
  shell: kubectl create secret generic my-secret --from-file=../Secrets.json

- name: Run Config file
  shell: kubectl create configmap my-config --from-file=../config.json


- name: Create replicationcontroller 
  shell: cat csye7374-ReplicationCOntroller.yaml | sed "s/xyz/{{accountid1.stdout}}/" | kubectl apply -f -
  args:
    chdir: ../k8s/app/

- name: Create service 
  shell: kubectl apply -f Service.yaml
  args:
    chdir: ../k8s/app/

    